### ISSUE TITLE
Please review your logic.

### ISSUE THREAD

**Issue by sheriff-rango** [prmali/NFT-Rarity-Scanner#2]
Hi.
This is Bikas Lin, a developer of hopres.io
I am using your python code for generating rarity rank for nfts on hopers.io and it was greatly helpful and saved lots of time.
But unfortunately, I have found some mismatching between generated rarity rank and original metadata.
So I would like you to review your code.
The metadata URL is the following.

https://hopegalaxy.mypinata.cloud/ipfs/QmX1i7DKeHyDHrnhFT8ab4E5mtfgtGH4XQ29ETi3WsGS5a/_metadata.json
https://hopegalaxy.mypinata.cloud/ipfs/QmSiJT5Jz9w55G3S2QUq5ZHz8VxsUFDN7VFYmUGF5U9LYR/_metadata.json

I would be very appreciative if you would test your code with these metadata and check the correctness.

**Comment by prmali** [comment]
Hey Bikas,

The metadata standards are different for what this script was originally built for (ERC-721), and what y'all are using: CW-721. Currently working on reproducing accurate rankings for different NFT metadata standards.

For the time being, I would appreciate if you can send over a list of differences, or the expected values.
Does the issue have to do with the token_id by any chance?

Thanks

**Comment by sheriff-rango** [comment]
![image](https://user-images.githubusercontent.com/95250818/182268682-2f0b5ef4-08e8-45ec-a68c-64167f3bc403.png)

As you can see from the image, the attributes for BAIC3D #472 in calculated data are not the same as the origin metadata(https://hopegalaxy.mypinata.cloud/ipfs/QmSiJT5Jz9w55G3S2QUq5ZHz8VxsUFDN7VFYmUGF5U9LYR/_metadata.json).

![image](https://user-images.githubusercontent.com/95250818/182269311-835d49e5-0f5e-4bba-bbe3-4a1502c2873d.png)

And there is no rarity info in calculated data for HexGorilla.457. (https://hopegalaxy.mypinata.cloud/ipfs/QmX1i7DKeHyDHrnhFT8ab4E5mtfgtGH4XQ29ETi3WsGS5a/_metadata.json)

**Comment by prmali** [comment]
Take a look at this and let me know if it works.
https://github.com/prmali/NFT-Rarity-Scanner/blob/master/src/client/aggregate/cw721.py

**Comment by sheriff-rango** [comment]
> Take a look at this and let me know if it works. https://github.com/prmali/NFT-Rarity-Scanner/blob/master/src/client/aggregate/cw721.py

Thanks, it works well.
